name: Generate GitHub Profile Trophy

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  trophy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: Guisilva29
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Trophy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          folder: .
          clean: false
          single-commit: true
          target-folder: trophy
